spring.application.name=E-Commerce-Auction
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:sqlserver://mysqlsprint01.database.windows.net:1433;database=SpringbootDB;user=CloudSA31716b8d@mysqlsprint01;password=root;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=groot
spring.datasource.password=groot123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
server.port = 8080